[run]
timeout = "10m"

[linters-settings.goconst]
min-len = 5
min-occurrences = 5

[linters-settings.exhaustive]
default-signifies-exhaustive = true

[linters-settings.revive]
ignore-generated-header = false
severity = "warning"
confidence = 3

[linters-settings.gocritic]
enabled-checks = ["ruleguard"]

[linters]
disable-all = true
enable = [
  "bodyclose",
  "dogsled",
  "errcheck",
  "gochecknoinits",
  "goconst",
  "gocritic",
  "goimports",
  "goprintffuncname",
  "gosimple",
  "govet",
  "ineffassign",
  "misspell",
  "nakedret",
  "exportloopref",
  "staticcheck",
  "stylecheck",
  "typecheck",
  "unconvert",
  "unused",
  "whitespace",
  "gocyclo",
  "exhaustive",
  "typecheck",
  "asciicheck",
  "errorlint",
  "revive",
]

[issues]
exclude-use-default = false

